<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChcParticipantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChcParticipantesRepository extends EntityRepository
{    
    public function findOneByPartidaAndUsuario($partida, $usuario)
    {
        $cb = $this->createQueryBuilder('ChCParticipantes');

        $cb->select('ChCParticipantes')
            ->where('ChCParticipantes.partida = :partida')
            ->andWhere('ChCParticipantes.usuario = :usuario')
            ->setParameter("partida", $partida)
            ->setParameter("usuario", $usuario)
            ->setMaxResults(1);
       
        return $cb->getQuery()->getOneOrNullResult();
    }
}
